### ISSUE TITLE
Typo in random forest article

### ISSUE THREAD

**Issue by teecrow** [aws-samples/aws-mlu-explain#24]
Hi there, great job with these visualizations -- excellent resource for those learning ML.

Small typo in the random forest article at https://mlu-explain.github.io/random-forest/ - looks like it was the author's note to themselves, but wasn't pulled before publishing.

![image](https://user-images.githubusercontent.com/51515693/184717175-2f18b4d7-2916-44d5-8df8-d11cba34b76b.png)

Keep up the good work!

**Comment by jwilber** [comment]
Fixed, thanks for letting me know!
