### ISSUE TITLE
Minor typo in the r-squared definition

### ISSUE THREAD

**Issue by amirdib** [aws-samples/aws-mlu-explain#35]
Hi there,

This latex equation

https://github.com/aws-samples/aws-mlu-explain/blob/8e3fcf6ce9a22fc754e8047ac3fcd8aa1833cbd7/code/linear-regression/src/Components/MeanSquaredError.svelte#L76
![image](https://user-images.githubusercontent.com/22154031/193414687-ab6aed9b-90d4-420a-b579-90bda4dcf062.png)

should be (removing the `i` sub for the mean in the `r^2` metric definition)

```latex 
 `\\begin{aligned} R^2 = 1 - \\frac{\\Sigma^{n}_{i=1}(y_i - \\hat{y_i})^2 }{\\Sigma^{n}_{i=1}(y_i - \\bar{y})^2 }  \\end{aligned}`, 
```

![image](https://user-images.githubusercontent.com/22154031/193414955-0d6934e5-3f3e-4139-93ba-679c4864976e.png)

**Comment by jwilber** [comment]
Fixed - thank you!
