### ISSUE TITLE
Typo in Linear Regression article

### ISSUE THREAD

**Issue by micaleel** [aws-samples/aws-mlu-explain#36]
In the first house prediction example on the [Linear Regression article](https://mlu-explain.github.io/linear-regression/), there's this [confusing statement](https://github.com/aws-samples/aws-mlu-explain/blob/main/code/linear-regression/src/Components/ScrollyRegression.svelte#L135-L136) that is probably a typo: 

> Of course we know this model is bad - **the data doesn't fit the data well at all**. But how can do quantify exactly how bad?

Was it meant to read "_the model doesn't fit the data well_"?

**Comment by jwilber** [comment]
Ty! Fixed
