### ISSUE TITLE
Minor potential number typo in Neural-networks article

### ISSUE THREAD

**Issue by logikblok** [aws-samples/aws-mlu-explain#56]
In the section **Activation Functions**

There is a [table presenting 4 functions](https://mlu-explain.github.io/neural-networks/#:~:text=popular%20activation%20functions%3A-,Name,-Plot). However the paragraph proceeding says:
>  Here are the three most popular activation functions: 

Should the number should be _four_ not _three_?

**Comment by jwilber** [comment]
Thank you! I originally didn't include step function - forgot to update the text after I added it back in. Updating now :)
