### ISSUE TITLE
Can not reproduce double descent phenomenon

### ISSUE THREAD

**Issue by 99991** [aws-samples/aws-mlu-explain#8]
I tried to reproduce the double descent phenomenon shown [here in the blog](https://mlu-explain.github.io/double-descent/) but have had no success so far.

![double_descent](https://user-images.githubusercontent.com/18725165/153564270-38aa88f0-66b1-4578-9fd4-86fb2faea63c.png)

The mean absolute error first decreases with more features and then grows only very slightly as the model overfits the training data set, which is what I would expect if double descent did not exist.

A thing I was not sure about were the "random non-linear features" mentioned in the blog. I chose scaled and shifted Tanh features since that was the first that came to my mind, but my MAE is slightly smaller than the one in the blog post, so maybe that is the issue? Which non-linear features have been used in the blog post?

Another potential issue could be insufficient regularization during matrix inversion since the problem is under-constrained with too many features. Maybe we are seeing numerical issues in the image from the blog post which get smoothed out with even more features? I'd imagine that with too many elements, numerical issues might behave like random noise, which has a regularizing effect.

![double_descent_from_blog](https://user-images.githubusercontent.com/18725165/153564263-b6cf0677-5aa2-4339-91e5-a65a9be400da.png)

Could you perhaps share the code which was used to generate the data shown in the figures from the blog? So far, I could only find [a file with the data](https://github.com/aws-samples/aws-mlu-explain/blob/main/code/double-descent/js/dataFiles.js), but not the code to generate it, although I did not look very hard. Maybe it is somewhere else or I did not recognize it.

For reproducibility, here is my code to generate my figure at the very top.

```python
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(0)
# Initialize data
x_train = np.linspace(-2, 2, 41)
y_train = np.float64([-20,-13,-7,-2,1,4,20,9,10,11,11,11,10,9,13,9,4,2,0,-1,-4,-6,-8,-11,-13,-15,-16,-18,-19,-19,-15,-19,-18,-17,-15,-13,0,-5,0,5,11])/10
x_test = np.linspace(-2, 2, 1000)
y_test = -0.4 - 2.27 * x_test + 0.76 * x_test**3
rand_vals = np.random.randn(100, 2)
MAE = []

def gen_rand_features(x):
    # Use scaled and shifted tanh as non-linear features
    return np.array([np.tanh(a * x + b) for a, b in rand_vals[:K]])

for K in range(1, 100):
    R = gen_rand_features(x_train)
    # Solve for weights of random features. 1e-10 seems to be sufficient
    # regularization to avoid numerical issues without influencing the result.
    weights = np.linalg.solve(R @ R.T + 1e-10 * np.eye(K), R @ y_train)
    y_prediction = gen_rand_features(x_test).T @ weights
    MAE.append(np.mean(np.abs(y_test - y_prediction)))

    if K == 33:
        plt.figure(figsize=(10, 4))
        plt.subplot(1, 2, 1)
        plt.title(f"Model with K = {K} Features")
        plt.plot(x_train, y_train, label="$y_{train}$")
        plt.plot(x_test, y_prediction, label="$y_{prediction}$")
        plt.legend()

        plt.subplot(1, 2, 2)
        plt.plot([np.log(K), np.log(K)], [0, 1], '--k', label=f"K = {K}")

plt.plot(np.log(np.arange(K) + 1), MAE)
plt.xlabel("Log(# of Non-linear Features)")
plt.ylabel("Mean Absolute Error")
plt.legend()
plt.ylim([0, 1])
plt.show()
```

**Comment by jwilber** [comment]
Hey Thomas,

Double Descent won't occur every time (I suppose that's part of the interest in the phenomena).
Can you shoot me an email? I'll send you the notebook underpinning our results.

Thanks!

(My email is wilber j w @ gmail.com with no spaces).
